# Generated by Django 5.1 on 2024-09-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="company/images/"
                    ),
                ),
                (
                    "line_notify",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
        ),
    ]
